### ISSUE TITLE
Building Docker containers

### ISSUE THREAD

**Issue by sevenearths** [KenMwaura1/zoo_Django_Actions#13]
https://github.com/KenMwaura1/zoo_Django_Actions/blob/a370c8bdeff233f5659371f16c1b87dd10a01cf1/.github/workflows/zoo_django_actions.yml#L105

Why are you building docker containers here at the end of the workflow? Is it just to test if the download and compile without breaking?

**Comment by KenMwaura1** [comment]
This ensures the docker containers run as intended
